# Generated by Django 3.1.6 on 2021-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_issue_tracking", "0008_auto_20210211_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("BE", "Back-end"),
                    ("FE", "Front-end"),
                    ("IO", "iOS"),
                    ("AN", "Android"),
                ],
                default="BE",
                max_length=2,
                verbose_name="Type",
            ),
        ),
    ]
