# Generated by Django 3.1.6 on 2021-02-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_issue_tracking", "0009_auto_20210211_1546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="permission",
            field=models.CharField(
                choices=[
                    ("NONE", "Aucune permission"),
                    ("READ", "Lecture uniquement"),
                    ("ALL", "Lecture & Ecriture"),
                ],
                default="ALL",
                max_length=10,
                verbose_name="Permission",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(
                choices=[("OWNER", "Responsable"), ("CONTRIB", "Contributeur")],
                default="OWNER",
                max_length=10,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("L", "Faible"), ("M", "Moyenne"), ("H", "Élevée")],
                default="L",
                max_length=1,
                verbose_name="Priorité",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "À faire"),
                    ("OPENED", "En cours"),
                    ("CLOSED", "Terminé"),
                ],
                default="TODO",
                max_length=6,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[("BUG", "Bug"), ("FEAT", "Amélioration"), ("TASK", "Tâche")],
                default="BUG",
                max_length=4,
                verbose_name="Balise",
            ),
        ),
    ]
