# Generated by Django 3.1.6 on 2021-02-17 19:07

import apps.api_issue_tracking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_issue_tracking", "0014_auto_20210215_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="permission",
            field=models.CharField(
                choices=[
                    ("NONE", "No permission"),
                    ("READ", "Read Only"),
                    ("ALL", "Read & Write"),
                ],
                default="ALL",
                max_length=10,
                verbose_name="Permission",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(
                choices=[("OWNER", "Administrator"), ("CONTRIB", "Contributor")],
                default="OWNER",
                max_length=10,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="assignee_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(apps.api_issue_tracking.models.get_sentinel_user),
                related_name="assignee_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="author_user",
            field=models.ForeignKey(
                on_delete=models.SET(apps.api_issue_tracking.models.get_sentinel_user),
                related_name="author_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default="L",
                max_length=1,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("TODO", "New"), ("OPENED", "Opened"), ("CLOSED", "Closed")],
                default="TODO",
                max_length=6,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[("BUG", "Bug"), ("FEAT", "Feature"), ("TASK", "Task")],
                default="BUG",
                max_length=4,
                verbose_name="Tag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("user", "project")},
        ),
    ]
