# Generated by Django 3.1.6 on 2021-02-19 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_issue_tracking", "0015_auto_20210217_1907"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Administrator"), ("CONTRIB", "Contributor")],
                default="ADMIN",
                max_length=10,
                verbose_name="Role",
            ),
        ),
    ]
